### ISSUE TITLE
更换书籍封面失败，存在跨域问题

### ISSUE THREAD

**Issue by JoanJiao** [TruthHun/BookStack#106]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
v2.7

2. 你当前使用的是什么操作系统?
ubuntu 18.04

3. 你是如何操作的？
用超级管理员（域名:8181端口访问）和作者账号都无法成功更换封面。其他功能正常。

4. 你期望得到什么结果?
能成功更换封面。

5. 当前遇到的是什么结果?
Chrome控制台错误提示：
```
Access to XMLHttpRequest at 'javascript:;' from origin 'http://域名.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
javascript:; Failed to load resource: net::ERR_FAILED
```
网上查了一下，说是存在跨域问题，但是我太小白了，看了几个讲解，实在搞不懂，特来求助

**Comment by lotustalk** [comment]
> 请按照一下格式提交issue，谢谢！
> 
> 1. 你当前使用的是哪个版本的 BookStack?
>    v2.7
> 2. 你当前使用的是什么操作系统?
>    ubuntu 18.04
> 3. 你是如何操作的？
>    用超级管理员（域名:8181端口访问）和作者账号都无法成功更换封面。其他功能正常。
> 4. 你期望得到什么结果?
>    能成功更换封面。
> 5. 当前遇到的是什么结果?
>    Chrome控制台错误提示：
> 
> ```
> Access to XMLHttpRequest at 'javascript:;' from origin 'http://域名.com' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
> javascript:; Failed to load resource: net::ERR_FAILED
> ```
> 
> 网上查了一下，说是存在跨域问题，但是我太小白了，看了几个讲解，实在搞不懂，特来求助

我解决了，通过配置nginx文件
