### ISSUE TITLE
编辑文档，图片上传成功了，uploads下对应的文件夹已经生成，但是图片没有移动到指定的路径下，日志也没有报错信息

### ISSUE THREAD

**Issue by cai-ti** [TruthHun/BookStack#138]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by vogin** [comment]
我在本地使用local，没有用oss，也遇到同样的问题解决了。
是运行目录与uploads不在一个层级。

比如 这样执行就不行
[root@xxx~] /www/wwwroot/BookStack/BookStack
比如cd /www/wwwroot/BookStack 然后 ./BookStack 运行，否则无法找到 uploads文件夹。

**Comment by cai-ti** [comment]
我用的自己写的docker-compose和dockerfile，代码路径存放的路径不对，导致读取文件的时候读取不到，但是在读文件的时候没把异常信息抛出来，已修复

**Comment by kpeng2016** [comment]
@cai-ti 我采用了https://github.com/willzhang/docker-bookstackcn的方法，也碰到了相同的问题，请问该怎么解决啊？
麻烦帮我看看啊，谢谢！！！
`FROM buildkite/puppeteer:10.0.0

ENV BOOKSTACK_VERSION=2.10 \
    LANG=C.UTF-8 \
    QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox"

WORKDIR /bookstack

RUN apt-get update -y \
    && apt-get install -y tzdata git \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && apt-get install -y ttf-wqy-zenhei fonts-wqy-microhei \
    && apt-get install -y python3 unzip xz-utils \
    && wget -qO /usr/local/bin/envsubst https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-Linux-x86_64 \    
    && chmod +x /usr/local/bin/envsubst \
    && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin \
    && wget https://github.com/TruthHun/BookStack/releases/download/v${BOOKSTACK_VERSION}/BookStack-V${BOOKSTACK_VERSION}_Linux_amd64.zip \
    && unzip BookStack-V${BOOKSTACK_VERSION}_Linux_amd64.zip \
    && chmod +x BookStack \
    && rm -rf BookStack-V${BOOKSTACK_VERSION}_Linux_amd64.zip \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

COPY conf/ /tmp/conf

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
EXPOSE 8181
CMD ["/bookstack/BookStack"]`
