### ISSUE TITLE
登录页面渲染问题 

### ISSUE THREAD

**Issue by thiswt** [TruthHun/BookStack#140]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.0

2. 你当前使用的是什么操作系统?
Windows

3. 你是如何操作的？
在Login方法添加一行如下代码开启注册即可  
this.Data["ENABLED_REGISTER"] = "true" 

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
[D] [controller.go:306]  template Execute err: template: account/login.html:70:29: executing "account/login.html" at <eq .ENABLED_REGISTER "true">: error calling eq: incompatible types for comparison 
[E] [server.go:2843]  template: account/login.html:70:29: executing "account/login.html" at <eq .ENABLED_REGISTER "true">: error calling eq: incompatible types for comparison

**Comment by 2191751138** [comment]
已经解决了 

在Login方法添加一行如下代码开启注册即可
this.Data["ENABLED_REGISTER"] = "true"
