### ISSUE TITLE
阅读能否增加密码访问

### ISSUE THREAD

**Issue by zanjs** [TruthHun/BookStack#15]
项目加密，可以设置项目公开状态，私有项目需要通过Token访问

**Comment by TruthHun** [comment]
现在就是这样。公开项目，谁都可以阅读。私有项目，只有根据带token的链接才能进行访问。私有项目，在项目设置里面，有个生成访问链接的功能。

**Comment by zanjs** [comment]
@TruthHun  好得 完美
