### ISSUE TITLE
新建项目，保存没有响应

### ISSUE THREAD

**Issue by aizaimenghuangu** [TruthHun/BookStack#2]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
BookStack_darwin_amd64

2. 你当前使用的是什么操作系统?
Mac 10.12.5 (16F73)

3. 你是如何操作的？
新建一个项目，点击保存按钮

4. 你期望得到什么结果?
能新建一个项目

5. 当前遇到的是什么结果?
保存按钮没有响应，仍然停留在当前页面
<img width="656" alt="wx20180302-225558 2x" src="https://user-images.githubusercontent.com/3993636/36905346-20f321fe-1e6e-11e8-9332-3c95459999af.png">

**Comment by TruthHun** [comment]
app.conf中的static_domain配置正确了吗？

**Comment by aizaimenghuangu** [comment]
1、目前在本地，配置的是static_domain=http://127.0.0.1:8181
2、在chrome上可以正常保存，但是在Safari下没有任何响应。

**Comment by aizaimenghuangu** [comment]
另外：修改封面的时候会提示如下错误：
```
2018/03/02 23:55:56 [E] [oss.go:127] 文件移动到OSS失败： Put http:/: http: no Host in request URL
2018/03/02 23:55:56 [E] [BookController.go:357] Put http:/: http: no Host in request URL
```

**Comment by TruthHun** [comment]
你配置了OSS了吗？目前暂时不支持本地存储。周末这两天在开发这个本地存储功能。

**Comment by aizaimenghuangu** [comment]
没有配置OSS，期待你的新版本，很看好这个项目，加油！
