### ISSUE TITLE
关于BookStack 和 DevOps tools 的集成问题

### ISSUE THREAD

**Issue by IBM-Ronnie** [TruthHun/BookStack#22]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
我正准备使用 BookStack

2. 你当前使用的是什么操作系统?
目前使用 RHEL 7

3. 你是如何操作的？
在学习研究阶段

4. 你期望得到什么结果?
BookStack 可以和 DevOps  的工具做集成吗？ 比如，和 Jenkins， Gitlab 等等。

5. 当前遇到的是什么结果?
没有查到资料可以和DevOps 的哪一个工具做集成

**Comment by TruthHun** [comment]
你好，Jenkins等我不熟，目前暂时没有和这些工具做集成的计划
