### ISSUE TITLE
私有项目成员列表显示bug

### ISSUE THREAD

**Issue by eoen** [TruthHun/BookStack#25]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
v1.2版本

2. 你当前使用的是什么操作系统?
ubuntu

3. 当前遇到的是什么结果?
私有项目的成员超过15个，页面不会显示以前添加的成员，也没有翻页按钮；
![huaban](https://user-images.githubusercontent.com/11888320/40710694-ec9b7ed4-642b-11e8-820b-244799488aff.png)

**Comment by TruthHun** [comment]
好的，这个问题，我下一版本处理一下。感谢反馈。

**Comment by TruthHun** [comment]
感谢反馈。问题在v1.5版本结局了。会在这两天内发布v1.5新版本
