### ISSUE TITLE
"一键导入markdown项目" 导入的文档只有标题，没有正文

### ISSUE THREAD

**Issue by bubbleatgit** [TruthHun/BookStack#26]
请按照一下格式提交issue，谢谢！

1.  当前使用的 bookstack 版本为 1.31
2.  当前部署环境为以 alpine 为基础镜像的容器
3.  用管理员账号创建项目后，点击“拉取项目”，填入 github 上的 markdown 仓库的 master.zip 的 url。
当后台任务完成后，查看前端页面，只显示标题，没有正文。
如图：
![image](https://user-images.githubusercontent.com/7858776/41845094-de77456c-78a4-11e8-8e1e-fdf33bd3cfc4.png)

但是点击编辑，可以看到正文内容
![image](https://user-images.githubusercontent.com/7858776/41845107-ec534604-78a4-11e8-83ff-2317f744bcdb.png)

希望能得到大佬们的帮助

**Comment by TruthHun** [comment]
需要点击发布才能看到内容。在保存的右边的那个按钮

**Comment by bubbleatgit** [comment]
1.  使用这个功能的文档，也需要点发布吗？
2.  我也尝试点过发布，就提示任务将在后台运行。但是前端还是老样子

**Comment by TruthHun** [comment]
我看了你的`dockerfile`，没安装Chrome。我的`dockerfile`(下一版本一同发布)：

```
FROM ubuntu:16.04

MAINTAINER "TruthHun <TruthHun@QQ.COM>"

# 安装字符编码支持
RUN apt update -y && apt install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

# 安装中文字体支持
RUN apt update -y && apt install -y fonts-wqy-zenhei fonts-wqy-microhei

# 安装calire和chromium-browser
RUN apt install -y xdg-utils wget xz-utils python chromium-browser \
    && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin

# 将程序拷贝进去
COPY . /www/BookStack/

# 将程序拷贝进去
COPY zoneinfo.zip /usr/local/go/lib/time/

RUN chmod 0777 -R /www/BookStack/

WORKDIR /www/BookStack/

RUN ./BookStack install

CMD [ "./BookStack" ]
```

**Comment by TruthHun** [comment]
安装下`chromium-browser`

**Comment by bubbleatgit** [comment]
ok，我还以为采集功能才需要chrome呢。感谢大佬！

**Comment by bubbleatgit** [comment]
关于Dockerfile，建议尽量 RUN 命令尽量写在同一个里面，这样可以较大程度降低 image 的容量大小。

**Comment by bubbleatgit** [comment]
经测试，安装chromium后，可正常显示了
