### ISSUE TITLE
能否发布编译好的Windows及Linux版本哇

### ISSUE THREAD

**Issue by aveyuan** [TruthHun/BookStack#28]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?
编译过程有点繁琐了，希望可以向mindoc那样发布编译的版本，便于直接使用，谢谢

5. 当前遇到的是什么结果?

**Comment by TruthHun** [comment]
https://github.com/TruthHun/BookStack/releases

**Comment by aveyuan** [comment]
没看到，谢谢
