### ISSUE TITLE
能否增加“版本升级部署”的操作说明

### ISSUE THREAD

**Issue by gdlwolf** [TruthHun/BookStack#4]
看了change.md后，非常期待新的版本，期待未来版本更多的功能。
但是目前的部署说明只有./BookStack install 安装。
如何在旧版本基础上升级为新版本（例如库结构是否需要升级），没有这方面的说明。
希望可以添加下说明，谢谢。

**Comment by TruthHun** [comment]
好的，会抽空整理一下文档。谢谢支持和认可。
