### ISSUE TITLE
生成下载文档失败

### ISSUE THREAD

**Issue by miaomiaoguoke** [TruthHun/BookStack#5]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
1.1

2. 你当前使用的是什么操作系统?
Centos 7

3. 你是如何操作的？
生成下载文档，cailre已正确安装，测试成功。

4. 你期望得到什么结果?
正确生成文档

5. 当前遇到的是什么结果?
2018/03/06 14:07:49 [E] [DocumentController.go:926] stat uploads/projects/bookstack/books/1520241164.epub: no such file or directory uploads/projects/bookstack/books/1520241164.epub 
2018/03/06 15:37:51 [E] [document.go:227] 下载文档生成时间跟文档发布时间一致，无需再重新生成下载文档 &{1 BookStack bookstack 0 这是一个BookStack演示项目，该项目是由系统初始化时自动创建。  0  0 markdown 2 closed 0 /static/images/book.png default 2018-03-05 10:23:38 +0800 CST 1 2018-03-05 10:23:38 +0800 CST 2018-03-05 17:12:44 +0800 CST 2018-03-05 17:12:44 +0800 CST 2018-03-06 14:02:53 +0800 CST 1520216618 12 0 40 0 0} 
2018/03/06 15:43:35 [E] [DocumentController.go:926] stat uploads/projects/bookstack/books/1520241164.pdf: no such file or directory uploads/projects/bookstack/books/1520241164.pdf

**Comment by TruthHun** [comment]
先“发布”，在生成下载文档。“发布”按钮就在保存按钮的右手边第一个。。

**Comment by miaomiaoguoke** [comment]
可以了，能否在生成文档的时候提醒下需要先发布呢。

**Comment by fenghongjian** [comment]
> 先“发布”，在生成下载文档。“发布”按钮就在保存按钮的右手边第一个。。

还是提示：
“错误：下载失败，您要下载的文档当前未生成任何可下载的文档”
求大神指点以下呀 
<img width="409" alt="截屏2021-02-09 下午7 59 54" src="https://user-images.githubusercontent.com/46391287/107484461-69072900-6bbd-11eb-8078-8fd4732f4d58.png">

**Comment by superabbite1** [comment]
我也是这个报错，下载失败，并未生成下载文档
