### ISSUE TITLE
centos7下部署后无法修改封面，且会导致浏览器卡死

### ISSUE THREAD

**Issue by aizaimenghuangu** [TruthHun/BookStack#6]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
1.1

2. 你当前使用的是什么操作系统?
项目部署在centos7
浏览器 mac OS 10.12.5 (16F73) 下的chrome和safari

3. 你是如何操作的？
在项目设置里面修改封面

4. 你期望得到什么结果?
正确修改封面

5. 当前遇到的是什么结果?
1. 控制台有看到以下成功信息：
{data: "/uploads/201803/1519606e15376803.jpg", errcode: 0, message: "ok", _raw: "{"data":"/uploads/201803/1519606e15376803.jpg","errcode":0,"message":"ok"}"}
2. 但是在uploads/201803/目录下没有生成对应的封面文件；
3. 此时：
a、如果浏览器是mac下的safari会导致浏览器卡死；
b、如果是windows下的浏览器，会出现当前页面有一个蒙版，无法继续操作；

**Comment by aizaimenghuangu** [comment]
后面发现是因为在centos7下，uploads目录被指向了/uploads  而不是我当前目录的./uploads

想咨询下这个uploads路径是如何指定的？

**Comment by aizaimenghuangu** [comment]
还找到了一个规律：
1. 如果是封面图片文件，则封面图片被保存到了/uploads;
2. 如果是文章中的图片文件，则被保存到了 ./uploads;

我这边的临时解决方案是：做软连接/uploads 到 项目目录下的uploads；

**Comment by TruthHun** [comment]
这个问题我稍后验证下。我是在mac下做的开发，然后部署在Ubuntu下的，mac和Ubuntu下测试的时候没遇到这个问题。目前手头上没有centos服务器，稍后我找台centos服务器测试验证下这个问题。

**Comment by aizaimenghuangu** [comment]
在Mac下上传图片封面，会有如下报错提示：
`/uploads/201803/151a46e67adaa2e2.png: no such file or directory`这个就是根目录下的uploads呀
```
[E] [BookController.go:383] rename uploads/201803/151a46e67adaa2e2.png /uploads/201803/151a46e67adaa2e2.png: no such file or directory
```

**Comment by aizaimenghuangu** [comment]
问题是不是出在BookController.go 383行，应该修改成：
```
if err := models.ModelStoreLocal.MoveToStore(url, save); err != nil {
```
否则会在跟目录下创建/uploads目录

```
case utils.StoreLocal:
		save := book.Cover
		//modified by xiongjinfei 
		if err := models.ModelStoreLocal.MoveToStore("."+url, save); err != nil {
			beego.Error(err.Error())
		} else {
			url = book.Cover
		}
```

**Comment by TruthHun** [comment]
谢谢提醒。已经对MoveToStore封装函数进行了修改，把`save`这个文件保存路径做了相对路径处理
