### ISSUE TITLE
一些优化建议

### ISSUE THREAD

**Issue by cc8ci** [TruthHun/BookStack#72]
**1.可以搜索私有项目。**
发现无法搜索私有项目，登录后也无法搜索到。
**2.设置登录后可以看的项目或者登录后才能查看公有项目。**
小团队或小公司大多数时候需要这个需求。比如我
**3.增加word导入功能。**
好多文档都是word写的，重新粘进去有点麻烦。

感谢作者~~~

**Comment by TruthHun** [comment]
mindoc针对的是文档管理，bookstack针对的是文档阅读，您可以了解下mindoc
