### ISSUE TITLE
验证码不显示是什么问题

### ISSUE THREAD

**Issue by myfengstyle** [TruthHun/BookStack#75]
验证码不显示是什么问题？

**Comment by Justice853** [comment]
同问

**Comment by TruthHun** [comment]
直接把程序所在根目录权限设置一下。如：
```
[sudo] chmod 0777 -R /www/wwwroot/www.bookstack.cn/
```

**Comment by fenghongjian** [comment]
安装完程序后，登陆时不显示验证码，求解决（或者能在后台把登陆时所需的验证码验证相关的功能替换掉）

<img width="1065" alt="截屏2020-11-25下午6 18 34" src="https://user-images.githubusercontent.com/46391287/100215494-09996580-2f4c-11eb-802a-7768c1b49180.png">
