### ISSUE TITLE
验证码不显示求解！！！！

### ISSUE THREAD

**Issue by Justice853** [TruthHun/BookStack#81]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.0

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
部署完成后，登陆界面验证码不显示

4. 你期望得到什么结果?
希望验证码可以显示

5. 当前遇到的是什么结果?
验证码不显示

**Comment by TruthHun** [comment]
直接把程序根目录设置 `777`权限。如：
```
sudo chmod 0777 -R /www/wwwroot/www.bookstack.cn/
```

**Comment by fenghongjian** [comment]
我的是ubuntu18.04的系统，安装完后也是不显示验证码，上网搜了很多解决办法，都失败了，最后按照您的方案尝试了一下，结果显示这个：，求大神指点一下，感谢了


 @TruthHun 
<img width="673" alt="截屏2020-11-25下午6 56 38" src="https://user-images.githubusercontent.com/46391287/100218820-30599b00-2f50-11eb-9bb4-f7a543f5ae70.png">
