### ISSUE TITLE
 爬虫无法使用呢

### ISSUE THREAD

**Issue by cqkenuo** [TruthHun/BookStack#82]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?

组新版
2. 你当前使用的是什么操作系统?

Linux
3. 你是如何操作的？
 爬虫无法使用

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by TruthHun** [comment]
请严格按照教程部署： https://www.bookstack.cn/read/help/Ubuntu.md
