### ISSUE TITLE
导出电子书封面修改信息

### ISSUE THREAD

**Issue by lichongbing** [TruthHun/BookStack#83]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
v2.4

2. 你当前使用的是什么操作系统?
ubuntu 16.4

3. 你是如何操作的？
导出epub文档

4. 你期望得到什么结果?
 想修改默认封面的水印

5. 当前遇到的是什么结果?
找不到在哪修改

**Comment by TruthHun** [comment]
`conf/app.conf` 修改下配置，以及`views/ebook`目录修改下相关信息
