### ISSUE TITLE
Github登录使用access token将于2020年7月1日停止支持，让用授权HTTP头

### ISSUE THREAD

**Issue by MFYDev** [TruthHun/BookStack#84]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 BookStack?
2.4

2. 你当前使用的是什么操作系统?
Ubuntu

3. 你是如何操作的？
使用Github登录

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

Github邮件提示我说access token将马上停止支持

On February 8th, 2020 at 04:22 (UTC) your application (BookStack) used an access token (with the User-Agent beegoServer) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

Depending on your API usage, we'll be sending you this email reminder once every 3 days.

Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.

Thanks,
The GitHub Team

**Comment by FanyangMengDev** [comment]
@TruthHun 我看您更新了Github登录的选项但是在更新之后并没有看到哪里改啊？并且最新版本的GIthub登录用不了啊
